language: go

go:
  - "1.15.x"
  - master

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

script:
  - go build -v ./...
  - go test -v -race -cover
  - $GOPATH/bin/goveralls -service=travis-ci
