name: Coverage

on:
  workflow_run:
    workflows: [ Test ]
    branches: [ main ]
    types: 
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go mod download
          go test -race -covermode atomic -coverprofile=covprofile ./...
          go get github.com/mattn/goveralls
          goveralls -coverprofile=covprofile -service=github
